\documentclass{article}
\begin{document}
    <?php echo $author; ?>

    \begin{table}[h!]
      \begin{center}
        \caption{Your first table.}
        \label{tab:table1}
        \begin{tabular}{l|c|r} % <-- Alignments: 1st column left, 2nd middle and 3rd right, with vertical lines in between
          \textbf{Value 1} & \textbf{Value 2} & \textbf{Value 3}\\
            A & B & C \\
            \hline';
            <?php
            foreach($table as $row) {
                echo $row[0].'&'.$row[1].'&'.$row[2].'\\\\'."\n";
            }
            ?>
        \end{tabular}
      \end{center}
    \end{table}
\end{document}
            
            
